FROM quay.io/ukhomeofficedigital/nodejs-base:v8

WORKDIR /test

COPY package.json package.json
COPY config.js config.js
COPY codecept.conf.js codecept.conf.js
COPY apps apps/
COPY assets assets/
COPY assets/countries/index.js assets/countries/index.js

RUN npm --loglevel warn install --ignore-scripts

CMD npm run hof-transpile

CMD npm run test:acceptance
